jasypt:
  encryptor:
    password: stringcatbepw

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://heejeong-database.cv35wjiwae1x.ap-northeast-2.rds.amazonaws.com:3306/stringcat?autoReconnect=true
    username: heejeong
    password: Stringcat-db
    dbcp2:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    hibernate:
      ddl-auto: none