spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: stringcat.be@gmail.com
    password: ENC(N2X2DlV4sz18ywREWBh/8jkx8GZxwWOa)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  profiles:
    active: local
    default: local
    include:
      - domain

server:
  port: 8100

swagger-info:
  title: stringcat
  description: stringcat REST API
  version: 1.0
