spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectionTimeout: 5000
          timeout: 5000
          writeTimeout: 5000
  profiles:
    active: local
    default: local
    include:
      - domain

server:
  port: 8100

swagger-info:
  title: stringcat
  description: stringcat REST API
  version: 1.0
