spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(c3RyaW5nY2F0LmJlQGdtYWlsLmNv)
    password: ENC(c3RyaW5nY2F0LTEy)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: local
    default: local
    include:
      - domain

server:
  port: 8100

swagger-info:
  title: stringcat
  description: stringcat REST API
  version: 1.0
