spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: stringcat.be@gmail.com
    password: stringcat-12
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: local
    default: local
    include:
      - domain

server:
  port: 8100

swagger-info:
  title: stringcat
  description: stringcat REST API
  version: 1.0
